package com.example.daykm.popmovies.greendao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.example.daykm.popmovies.greendao.FavoriteMovie;

import com.example.daykm.popmovies.greendao.FavoriteMovieDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig favoriteMovieDaoConfig;

    private final FavoriteMovieDao favoriteMovieDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        favoriteMovieDaoConfig = daoConfigMap.get(FavoriteMovieDao.class).clone();
        favoriteMovieDaoConfig.initIdentityScope(type);

        favoriteMovieDao = new FavoriteMovieDao(favoriteMovieDaoConfig, this);

        registerDao(FavoriteMovie.class, favoriteMovieDao);
    }
    
    public void clear() {
        favoriteMovieDaoConfig.getIdentityScope().clear();
    }

    public FavoriteMovieDao getFavoriteMovieDao() {
        return favoriteMovieDao;
    }

}
