package com.example.daykm.popmovies.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "FAVORITE_MOVIE".
 */
public class FavoriteMovie {

    private Long id;
    private Integer movieid;

    public FavoriteMovie() {
    }

    public FavoriteMovie(Long id) {
        this.id = id;
    }

    public FavoriteMovie(Long id, Integer movieid) {
        this.id = id;
        this.movieid = movieid;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getMovieid() {
        return movieid;
    }

    public void setMovieid(Integer movieid) {
        this.movieid = movieid;
    }

}
